// EmergencyQRView.swift
// Petpal - Emergency QR Code & Profile Management
 
import SwiftUI
import SwiftData
import CoreImage.CIFilterBuiltins
#if os(iOS)
import UIKit
#endif
#if os(macOS)
import AppKit
#endif
 
struct EmergencyQRView: View {
    @Environment(\.modelContext) private var modelContext
    @Environment(\.dismiss) private var dismiss
    @AppStorage("petName") private var petName: String = "Your Pet"
 
    @Query private var emergencyProfiles: [EmergencyProfile]
    @Query(sort: \Pet.dateAdded) private var pets: [Pet]
    @State private var showingEditor = false
    @State private var qrImageData: Data?
    #if os(iOS)
    @State private var sharePayload: ShareSheetPayload?
    #endif
    
    /// Emergency profile for the pet shown on Home / switched in-tab only.
    private var profilesForActivePet: [EmergencyProfile] {
        guard let pid = FeaturePetScope.resolvedPetId(pets: pets) else { return [] }
        return emergencyProfiles.filter { $0.linkedPetId == pid }
    }
 
    var currentProfile: EmergencyProfile? {
        profilesForActivePet.first { $0.isActive } ?? profilesForActivePet.first
    }
 
    var body: some View {
        NavigationStack {
            ZStack {
                LinearGradient(
                    colors: [Color("BrandCream"), Color("BrandSoftBlue").opacity(0.3)],
                    startPoint: .topLeading,
                    endPoint: .bottomTrailing
                )
                .ignoresSafeArea()
 
                VStack(alignment: .leading, spacing: 0) {
                    FeaturePetScopeHeader(pets: pets)
                    Text("Printable QR for lost pet with vital info")
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .padding(.horizontal, 20)
                        .padding(.top, 4)
                        .padding(.bottom, 8)
                    if let profile = currentProfile {
                        ScrollView {
                            VStack(spacing: 24) {
                                headerSection
                            qrCodeCard(profile: profile)
                            profileSummaryCard(profile: profile)
                            instructionsCard
                        }
                        .padding()
                    }
                    } else {
                        emptyStateView
                    }
                }
            }
            .navigationTitle("Emergency QR")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Close") { dismiss() }
                }
                ToolbarItem(placement: .primaryAction) {
                    HStack(spacing: 12) {
                        #if os(iOS)
                        if let profile = currentProfile {
                            Menu {
                                Button {
                                    let printable = EmergencyQRPrintableView(profile: profile)
                                    if let img = PrintShareHelper.renderToImage(printable) {
                                        let text = "Emergency QR for \(profile.petName) — Generated by Petpal"
                                        DispatchQueue.main.async {
                                            sharePayload = ShareSheetPayload(items: [img, text])
                                        }
                                    }
                                } label: {
                                    Label("Share", systemImage: "square.and.arrow.up")
                                }
                                Button {
                                    let printable = EmergencyQRPrintableView(profile: profile)
                                    DispatchQueue.main.async {
                                        PrintShareHelper.printView(printable, title: "Emergency QR")
                                    }
                                } label: {
                                    Label("Print", systemImage: "printer")
                                }
                            } label: {
                                Image(systemName: "ellipsis.circle")
                            }
                        }
                        #endif
                        Button {
                            showingEditor = true
                        } label: {
                            Image(systemName: currentProfile == nil ? "plus.circle.fill" : "pencil.circle.fill")
                                .font(.title2)
                                .foregroundStyle(Color("BrandOrange"))
                        }
                    }
                }
            }
            .sheet(isPresented: $showingEditor) {
                EmergencyProfileEditor(profile: currentProfile)
            }
            #if os(iOS)
            .sheet(item: $sharePayload) { payload in
                ShareSheet(items: payload.items)
            }
            #endif
            .onAppear {
                migrateLegacyEmergencyProfilesIfNeeded()
            }
        }
    }
    
    /// Split legacy global profiles into one copy per pet (same pattern as Pet Care Notes).
    private func migrateLegacyEmergencyProfilesIfNeeded() {
        let orphans = emergencyProfiles.filter { $0.linkedPetId == nil }
        var petsWithProfile = Set(emergencyProfiles.compactMap { $0.linkedPetId })
        
        if let template = orphans.first, !pets.isEmpty {
            for pet in pets where !petsWithProfile.contains(pet.id) {
                modelContext.insert(Self.duplicateEmergencyProfile(template, linkedPetId: pet.id))
                petsWithProfile.insert(pet.id)
            }
            for o in orphans {
                modelContext.delete(o)
            }
            try? modelContext.save()
            return
        }
        
        if let pid = FeaturePetScope.resolvedPetId(pets: pets), !emergencyProfiles.contains(where: { $0.linkedPetId == pid }) {
            let new = EmergencyProfile(linkedPetId: pid, petName: petName)
            modelContext.insert(new)
            try? modelContext.save()
        }
    }
    
    private static func duplicateEmergencyProfile(_ template: EmergencyProfile, linkedPetId: UUID) -> EmergencyProfile {
        EmergencyProfile(
            linkedPetId: linkedPetId,
            petName: template.petName,
            ownerName: template.ownerName,
            ownerPhone: template.ownerPhone,
            ownerEmail: template.ownerEmail,
            alternateContact: template.alternateContact,
            medications: template.medications,
            allergies: template.allergies,
            medicalConditions: template.medicalConditions,
            microchipNumber: template.microchipNumber,
            vetName: template.vetName,
            vetPhone: template.vetPhone,
            vetAddress: template.vetAddress,
            feedingInstructions: template.feedingInstructions,
            specialNeeds: template.specialNeeds,
            lostPetMessage: template.lostPetMessage,
            rewardOffered: template.rewardOffered,
            isActive: template.isActive,
            lastUpdated: template.lastUpdated
        )
    }
 
    private var headerSection: some View {
        VStack(spacing: 8) {
            Image(systemName: "qrcode")
                .font(.system(size: 50))
                .foregroundStyle(Color("BrandOrange"))
            Text("Emergency Collar Tag")
                .font(.title2)
                .fontWeight(.bold)
                .foregroundStyle(Color("BrandDark"))
            Text("Print and attach to your pet's collar")
                .font(.subheadline)
                .foregroundStyle(.secondary)
        }
        .padding()
    }
 
    private func qrCodeCard(profile: EmergencyProfile) -> some View {
        VStack(spacing: 16) {
            Text("Scan to View Emergency Info")
                .font(.headline)
                .foregroundStyle(Color("BrandDark"))
 
            if let data = generateQRCode(from: profile.emergencyURL) {
                qrCodeImage(from: data)
                    .padding()
                    .background(Color.white)
                    .cornerRadius(16)
                    .shadow(color: Color.black.opacity(0.1), radius: 8)
                    .onAppear { qrImageData = data }
            }
 
            Text(profile.petName)
                .font(.title3)
                .fontWeight(.bold)
                .foregroundStyle(Color("BrandOrange"))
 
            HStack(spacing: 16) {
                Button {
                    #if os(iOS)
                    if let data = qrImageData, let image = UIImage(data: data) {
                        let text = "Emergency contact for \(profile.petName) — Generated by Petpal"
                        DispatchQueue.main.async {
                            sharePayload = ShareSheetPayload(items: [image, text])
                        }
                    }
                    #endif
                } label: {
                    Label("Share", systemImage: "square.and.arrow.up")
                        .font(.headline)
                        .foregroundStyle(.white)
                        .padding(.horizontal, 24)
                        .padding(.vertical, 12)
                        .background(Color("BrandOrange"))
                        .clipShape(Capsule())
                }
 
                Button {
                    #if os(iOS)
                    if let data = qrImageData, let image = UIImage(data: data) {
                        UIImageWriteToSavedPhotosAlbum(image, nil, nil, nil)
                    }
                    #endif
                } label: {
                    Label("Save", systemImage: "square.and.arrow.down")
                        .font(.headline)
                        .foregroundStyle(Color("BrandOrange"))
                        .padding(.horizontal, 24)
                        .padding(.vertical, 12)
                        .background(Color("BrandOrange").opacity(0.15))
                        .clipShape(Capsule())
                }
            }
        }
        .padding()
        .background(qrCardBackgroundColor)
        .clipShape(RoundedRectangle(cornerRadius: 20))
        .shadow(color: Color.black.opacity(0.07), radius: 8, x: 0, y: 4)
    }
 
    private var qrCardBackgroundColor: Color {
        #if os(iOS)
        return Color(.systemBackground)
        #elseif os(macOS)
        return Color(nsColor: .windowBackgroundColor)
        #else
        return Color.white
        #endif
    }
 
    private func profileSummaryCard(profile: EmergencyProfile) -> some View {
        VStack(alignment: .leading, spacing: 16) {
            HStack {
                Image(systemName: "info.circle.fill")
                    .foregroundStyle(Color("BrandBlue"))
                Text("Emergency Info Summary")
                    .font(.headline)
                    .foregroundStyle(Color("BrandDark"))
            }
 
            VStack(alignment: .leading, spacing: 12) {
                if !profile.ownerPhone.isEmpty {
                    EmergencyInfoRow(icon: "phone.fill", label: "Owner", value: profile.ownerPhone)
                }
                if !profile.vetPhone.isEmpty {
                    EmergencyInfoRow(icon: "cross.case.fill", label: "Vet", value: profile.vetPhone)
                }
                if !profile.medications.isEmpty {
                    EmergencyInfoRow(icon: "pills.fill", label: "Medications", value: profile.medications)
                }
                if !profile.allergies.isEmpty {
                    EmergencyInfoRow(icon: "exclamationmark.triangle.fill", label: "Allergies", value: profile.allergies, color: .red)
                }
                if !profile.microchipNumber.isEmpty {
                    EmergencyInfoRow(icon: "antenna.radiowaves.left.and.right", label: "Microchip", value: profile.microchipNumber)
                }
            }
 
            Button {
                showingEditor = true
            } label: {
                HStack {
                    Image(systemName: "pencil")
                    Text("Edit Emergency Info")
                }
                .font(.subheadline)
                .foregroundStyle(Color("BrandOrange"))
            }
        }
        .padding()
        .background(qrCardBackgroundColor)
        .clipShape(RoundedRectangle(cornerRadius: 20))
        .shadow(color: Color.black.opacity(0.07), radius: 8, x: 0, y: 4)
    }
 
    private var instructionsCard: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack {
                Image(systemName: "lightbulb.fill")
                    .foregroundStyle(Color("BrandOrange"))
                Text("How to Use")
                    .font(.headline)
                    .foregroundStyle(Color("BrandDark"))
            }
 
            VStack(alignment: .leading, spacing: 8) {
                InstructionRow(number: "1", text: "Save or print the QR code")
                InstructionRow(number: "2", text: "Attach to your pet's collar tag")
                InstructionRow(number: "3", text: "Anyone can scan to see emergency info")
                InstructionRow(number: "4", text: "They'll also discover Petpal!")
            }
 
            Text("Tip: Laminate the printed tag for durability")
                .font(.caption)
                .foregroundStyle(.secondary)
                .padding(.top, 4)
        }
        .padding()
        .background(qrCardBackgroundColor)
        .clipShape(RoundedRectangle(cornerRadius: 20))
        .shadow(color: Color.black.opacity(0.07), radius: 8, x: 0, y: 4)
    }
 
    private var emptyStateView: some View {
        VStack(spacing: 20) {
            Image(systemName: "qrcode")
                .font(.system(size: 60))
                .foregroundStyle(Color("BrandOrange").opacity(0.5))
            Text("No Emergency Profile")
                .font(.title2)
                .fontWeight(.bold)
                .foregroundStyle(Color("BrandDark"))
            Text("Create an emergency profile to generate a QR code for your pet's collar.")
                .font(.subheadline)
                .foregroundStyle(.secondary)
                .multilineTextAlignment(.center)
                .padding(.horizontal, 40)
            Button {
                showingEditor = true
            } label: {
                Label("Create Profile", systemImage: "plus.circle.fill")
                    .font(.headline)
                    .foregroundStyle(.white)
                    .padding(.horizontal, 24)
                    .padding(.vertical, 12)
                    .background(Color("BrandOrange"))
                    .clipShape(Capsule())
            }
        }
        .frame(maxHeight: .infinity)
    }
 
    @ViewBuilder
    private func qrCodeImage(from data: Data) -> some View {
        #if os(iOS)
        if let uiImage = UIImage(data: data) {
            Image(uiImage: uiImage)
                .interpolation(.none)
                .resizable()
                .scaledToFit()
                .frame(width: 250, height: 250)
        } else {
            Image(systemName: "qrcode")
                .resizable()
                .scaledToFit()
                .frame(width: 250, height: 250)
        }
        #elseif os(macOS)
        if let nsImage = NSImage(data: data) {
            Image(nsImage: nsImage)
                .interpolation(.none)
                .resizable()
                .scaledToFit()
                .frame(width: 250, height: 250)
        } else {
            Image(systemName: "qrcode")
                .resizable()
                .scaledToFit()
                .frame(width: 250, height: 250)
        }
        #endif
    }
 
    private func generateQRCode(from string: String) -> Data? {
        let context = CIContext()
        let filter = CIFilter.qrCodeGenerator()
        filter.message = Data(string.utf8)
        filter.correctionLevel = "H"
        guard let outputImage = filter.outputImage else { return nil }
        let scaledImage = outputImage.transformed(by: CGAffineTransform(scaleX: 10, y: 10))
        guard let cgImage = context.createCGImage(scaledImage, from: scaledImage.extent) else { return nil }
        #if os(iOS)
        return UIImage(cgImage: cgImage).pngData()
        #elseif os(macOS)
        let nsImage = NSImage(cgImage: cgImage, size: NSSize(width: cgImage.width, height: cgImage.height))
        return nsImage.tiffRepresentation
        #else
        return nil
        #endif
    }
}
 
// MARK: - Printable View
 
#if os(iOS)
private struct EmergencyQRPrintableView: View {
    let profile: EmergencyProfile

    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            Text("Emergency Collar Tag")
                .font(.title2)
                .fontWeight(.bold)
                .foregroundStyle(Color.black)
            Text("Scan QR to view emergency info — Print and attach to collar")
                .font(.caption)
                .foregroundStyle(Color.black.opacity(0.7))
            Divider()
            if let data = Self.generateQRCode(from: profile.emergencyURL),
               let uiImage = UIImage(data: data) {
                Image(uiImage: uiImage)
                    .interpolation(.none)
                    .resizable()
                    .scaledToFit()
                    .frame(width: 200, height: 200)
            }
            Text(profile.petName)
                .font(.title3)
                .fontWeight(.bold)
                .foregroundStyle(Color.black)
            VStack(alignment: .leading, spacing: 8) {
                if !profile.ownerPhone.isEmpty {
                    row("Owner", profile.ownerPhone)
                }
                if !profile.vetPhone.isEmpty {
                    row("Vet", profile.vetPhone)
                }
                if !profile.medications.isEmpty {
                    row("Medications", profile.medications)
                }
                if !profile.allergies.isEmpty {
                    row("Allergies", profile.allergies)
                }
                if !profile.microchipNumber.isEmpty {
                    row("Microchip", profile.microchipNumber)
                }
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding()
        .background(Color.white)
        .preferredColorScheme(.light)
    }

    private func row(_ label: String, _ value: String) -> some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(label)
                .font(.caption)
                .foregroundStyle(Color.black.opacity(0.6))
            Text(value)
                .font(.subheadline)
                .foregroundStyle(Color.black)
                .frame(maxWidth: .infinity, alignment: .leading)
                .fixedSize(horizontal: false, vertical: true)
        }
    }

    static func generateQRCode(from string: String) -> Data? {
        let context = CIContext()
        let filter = CIFilter.qrCodeGenerator()
        filter.message = Data(string.utf8)
        filter.correctionLevel = "H"
        guard let outputImage = filter.outputImage else { return nil }
        let scaledImage = outputImage.transformed(by: CGAffineTransform(scaleX: 10, y: 10))
        guard let cgImage = context.createCGImage(scaledImage, from: scaledImage.extent) else { return nil }
        return UIImage(cgImage: cgImage).pngData()
    }
}
#endif

// MARK: - Supporting Views
 
struct EmergencyInfoRow: View {
    let icon: String
    let label: String
    let value: String
    var color: Color = Color("BrandBlue")
 
    var body: some View {
        HStack(spacing: 12) {
            Image(systemName: icon)
                .font(.caption)
                .foregroundStyle(color)
                .frame(width: 20)
            VStack(alignment: .leading, spacing: 2) {
                Text(label)
                    .font(.caption)
                    .foregroundStyle(.secondary)
                Text(value)
                    .font(.subheadline)
                    .foregroundStyle(Color("BrandDark"))
            }
        }
    }
}
 
struct InstructionRow: View {
    let number: String
    let text: String
 
    var body: some View {
        HStack(alignment: .top, spacing: 12) {
            Text(number)
                .font(.caption)
                .fontWeight(.bold)
                .foregroundStyle(.white)
                .frame(width: 24, height: 24)
                .background(Color("BrandOrange"))
                .clipShape(Circle())
            Text(text)
                .font(.subheadline)
                .foregroundStyle(Color("BrandDark"))
        }
    }
}

#Preview {
    EmergencyQRView()
        .modelContainer(for: EmergencyProfile.self, inMemory: true)
}
